#!/usr/bin/env python3
"""Builder for mlrv-pd/abstractions/file_browser.pd -- sample browser indexed list."""
import sys
sys.path.insert(0, __file__.rsplit("/", 1)[0])
from pdgen import Patch
import os
OUT = "/home/aandi/repos/mlrv--/mlrv-pd/abstractions/file_browser.pd"
if os.path.exists(OUT):
    os.remove(OUT)
p = Patch(w=1300, h=900)
inp = p.obj(20, 20, "inlet")
route = p.obj(20, 60, "route add slot file load clear dir open")
p.connect(inp, 0, route, 0)
txtDefine = p.obj(700, 20, "text define filelist")
txtSet = p.obj(300, 320, "text set filelist")
txtGet = p.obj(450, 280, "text get filelist")
next_idx = p.obj(200, 120, "float 0")
sel_slot = p.obj(350, 120, "float 0")
sel_file = p.obj(500, 120, "float 0")
dir_store = p.obj(650, 120, "symbol")
out_load = p.obj(20, 800, "outlet")
out_display = p.obj(200, 800, "outlet")
print_add = p.obj(20, 750, "print fb_add")
print_load = p.obj(350, 750, "print fb_load")
t_add = p.obj(20, 120, "t a b")
t_dup = p.obj(200, 200, "t f f")
inc = p.obj(200, 260, "+ 1")
print_add2 = p.obj(100, 750, "print fb_added_file")
t_load = p.obj(500, 200, "t b b")
pack_load = p.obj(400, 400, "pack f s")
msg_load = p.msg(400, 480, "load \\$1 \\$2")
t_clear = p.obj(300, 240, "t b b")
msg_clear = p.msg(300, 300, "clear")
msg_zero = p.msg(200, 300, "0")
openpanel = p.obj(600, 180, "openpanel")
listConv = p.obj(100, 200, "list")
unpackConv = p.obj(450, 340, "unpack s")
# add
p.connect(route, 0, t_add, 0)
p.connect(t_add, 1, next_idx, 0)
p.connect(t_add, 0, listConv, 0)
p.connect(listConv, 0, txtSet, 0)
p.connect(next_idx, 0, t_dup, 0)
p.connect(t_dup, 1, txtSet, 1)
p.connect(t_dup, 0, inc, 0)
p.connect(inc, 0, next_idx, 1)
p.connect(listConv, 0, print_add2, 0)
# slot/file silent store
p.connect(route, 1, sel_slot, 1)
p.connect(route, 2, sel_file, 1)
# load
p.connect(route, 3, t_load, 0)
p.connect(t_load, 1, sel_file, 0)
p.connect(sel_file, 0, txtGet, 0)
p.connect(txtGet, 0, unpackConv, 0)
p.connect(unpackConv, 0, pack_load, 1)
p.connect(sel_slot, 0, pack_load, 0)
p.connect(pack_load, 0, msg_load, 0)
p.connect(msg_load, 0, out_load, 0)
p.connect(msg_load, 0, print_load, 0)
p.connect(t_load, 0, sel_slot, 0)
# clear
p.connect(route, 4, t_clear, 0)
p.connect(t_clear, 1, msg_clear, 0)
p.connect(msg_clear, 0, txtDefine, 0)
p.connect(t_clear, 0, msg_zero, 0)
p.connect(msg_zero, 0, next_idx, 0)
# dir
p.connect(route, 5, dir_store, 0)
# openpanel
p.connect(route, 6, openpanel, 0)
p.connect(openpanel, 0, t_add, 0)
p.write(OUT)
print("wrote file_browser indexed v3")
