#!/bin/bash
OUT=/home/aandi/repos/mlrv--/mlrv-pd/frontends/assets/embedded-pd.js
echo "// Auto-generated by embed-pd.sh — do not edit by hand." > "$OUT"
echo "// Source .pd files inlined so patch-graph.html works over file:// URLs." >> "$OUT"
echo "// Keys match the dropdown values in patch-graph.html (relative to frontends/)." >> "$OUT"
echo "window.MLRV_EMBEDDED_PD = {" >> "$OUT"

REPO=/home/aandi/repos/mlrv--/mlrv-pd
# Keys = same strings used in the <option value="..."> in patch-graph.html
declare -a FILES=(
  "../mlrv.pd"
  "../patchers/serialosc.pd"
  "../patchers/file_poly.pd"
  "../patchers/mapping.pd"
  "../patchers/grid.pd"
  "../abstractions/mixer.pd"
  "../abstractions/master.pd"
  "../abstractions/play_loop~.pd"
  "../abstractions/sample_voice~.pd"
)
declare -a PATHS=(
  "$REPO/mlrv.pd"
  "$REPO/patchers/serialosc.pd"
  "$REPO/patchers/file_poly.pd"
  "$REPO/patchers/mapping.pd"
  "$REPO/patchers/grid.pd"
  "$REPO/abstractions/mixer.pd"
  "$REPO/abstractions/master.pd"
  "$REPO/abstractions/play_loop~.pd"
  "$REPO/abstractions/sample_voice~.pd"
)

for i in "${!FILES[@]}"; do
  key="${FILES[$i]}"
  path="${PATHS[$i]}"
  python3 -c "
import sys
content = open(sys.argv[1], 'rb').read().decode('utf-8', errors='replace')
# Escape characters that would break a JS template literal
escaped = content.replace('\\\\', '\\\\\\\\').replace('\`', '\\\\\`').replace('\$', '\\\\\$')
print(f'  \"{sys.argv[2]}\": \`{escaped}\`,')
" "$path" "$key" >> "$OUT"
done

echo "};" >> "$OUT"
